name: ssc_invoice_app
description: SSC Master Flutter Developer - zadanie rekrutacyjne
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  get_it: ^8.0.1
  injectable: ^2.4.2
  go_router: ^14.3.0
  isar: ^3.1.0+1
  isar_flutter_libs:
    git:
      url: https://github.com/Deepjyoti120/isar_flutter_libs.git
      ref: main
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  uuid: ^4.5.0
  collection: ^1.18.0
  equatable: ^2.0.7
  open_filex: ^4.7.0
  dartz: ^0.10.1

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.4.7
  isar_generator: ^3.1.0+1
  injectable_generator: ^2.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_ssc.png
